image: node:8.11.3

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm install

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
  - CI=true npm test -- --coverage

build:
  stage: build
  script:
  - CI=true npm run build
  artifacts:
    paths:
    - build

pages:
  stage: deploy
  dependencies:
    - build
  script:
  - rm -rf public
  - mv build public
  artifacts:
    paths:
    - public
